### ISSUE TITLE
Mapping combination of keys

### ISSUE THREAD

**Issue by BlessedGeek** [stuartd/keymapper#15]
Unable to map combination of keys.
e.g. the Hebrew niqud vowel points are produced with combination of CapsLock+Shift+{a number row key}.
Using the CapsLock is inconvenient. I need to remap them to Ctrl+Shift{a number row key}.

**Comment by stuartd** [comment]
KeyMapper can't do that, the underlying Windows mechanism it uses to remap keys only allows one key to be changed, not a combination: you can remap "shift" or "capslock" or a number key, but you can't remap a combination of them.

Generally for this I recommend trying [AutoHotKey](https://www.autohotkey.com/) - I believe it can do this as it sits in the background and can intercept multiplr keystrokes.

Disclaimer: I don't use it personally.
