### ISSUE TITLE
No altgr support?

### ISSUE THREAD

**Issue by Elronnd** [stuartd/keymapper#16]
I want to remap caps-lock to emit altgr, but I can't seem to find an altgr anywhere?

**Comment by stuartd** [comment]
This is I think keyboard locale specific, but on US keyboards they're categorised as "Left Alt" and "Right Alt" where "Right Alt" is labelled "Alt Gr"

![image](https://user-images.githubusercontent.com/275326/56276522-2aec6b80-60f2-11e9-84b4-d35b22b96942.png)
