### ISSUE TITLE
Mapping Capslock to Break

### ISSUE THREAD

**Issue by Aoxo** [stuartd/keymapper#17]
I mapped capslock to break, hoping to use it as a push to talk bind in games.  Unfortunately now pressing capslock activates the break key but releasing capslock doesn't release the break key.  I have to press the real break key to trigger a release.  This makes the whole idea of rebinding my caps pointless and broken.  Is there a way to fix the behavior of the button so it will release as well as press?

**Comment by stuartd** [comment]
Sorry, no. That's not the way keyboard mappings work. You would have to press CapsLock again to release it, just as if you used the real break key.

For something like this you could use [AutoHotKey](https://www.autohotkey.com/docs/AutoHotkey.htm) as that allows you to assign different actions to KeyDown and KeyUp.
