### ISSUE TITLE
Keymapper doesn't install on Windows 10

### ISSUE THREAD

**Issue by fejoalse** [stuartd/keymapper#18]
Hi! The keymapper isn't installing on Windows 10 64 bits. What's the matter? Thanks.

**Comment by stuartd** [comment]
Are you using the MSI installer from a download site? Because since Google Code was retired, they haven't been available. KM doesn't really need an installer, there's a simple EXE file [here](https://github.com/stuartd/keymapper/blob/develop/KeyMapper.exe)

**Comment by fejoalse** [comment]
I've been trying to install this EXE file since the begin,, but it doesn't install on my Windows 10.  That's ok on the same machine with Windows 7.

**Comment by stuartd** [comment]
The EXE doesn't install, it just runs. If you're seeing an error message can you add it in here? If not is there a log in `%appdata%\Rose Hill Solutions`? (You can paste that into the directory bar in Windows Explorer)

Otherwise, can you run the EXE and then look in the Windows Event Log for any error message?

**Comment by fejoalse** [comment]
Hello! That's right! My apologize. Actually it just runs. It runs on windows 7, but it doesn't run on winddows 10. No error message appears, but there are a log error and an user.config file in user\AppData\local\
\Rose_Hill_Solutions\KeyMapper.exe_StrongName_awasmzssygzhap4ytfdi0ipixoixoef4\1.0.0.0\user.config (see below).  When I click keymapper.exe it seems to start working, but it stops and it doesn't work. There is not any result.  It doesn't  open. I found an error in the Windows Event Log ( See file below):
[Report_wer.txt](https://github.com/stuartd/keymapper/files/3715480/Report_wer.txt)
[Event_evtx.txt](https://github.com/stuartd/keymapper/files/3715486/Event_evtx.txt)

[userconfig_Win10.txt](https://github.com/stuartd/keymapper/files/3714436/userconfig_Win10.txt)
[userconfig_Win7.txt](https://github.com/stuartd/keymapper/files/3714450/userconfig_Win7.txt)

**Comment by stuartd** [comment]
Thanks for the logs! I've looked at those though and I'm not seeing anything the helps diagnose the problem :-(

The fact that the error is in the event log means KeyMapper won't even start - as if it did start and there was an error, then it would catch the error and write it to `AppData\**Roaming**\Rose Hill Solutions\debug.txt`. 

I'm not sure what else can be done. I'll have a think about it though.

I wonder was this PC upgraded to Windows 10, and was that when it stopped working? It certainly _does_ work on Windows 10, but I've never tested it after an upgrade from Windows 7.

**Comment by fejoalse** [comment]
Hi! Thank you for your answer. There isn't any debug file. My HP notebook wasn't upgraded  to Windows 10. There are two partitions. The first with Windows 7 and the second with Windows 10. I remembered that I have another desktop PC Dell in the same conditions with 2 partitions. The result is exactly the same. Ok on Windows 7 and failure on WIndows 10. I don't have a PC with only Windows 10 installed for testing. I don't know what's happening. Very strange.
