### ISSUE TITLE
where the fuck is the exe

### ISSUE THREAD

**Issue by slingring** [stuartd/keymapper#22]
This is why i dont install shit off of github you pajeets, i cant find the EXE file. and your shitty readme explains nothing.

**Comment by stuartd** [comment]
It is there. but it's not very clear I admit. 

![image](https://user-images.githubusercontent.com/275326/108353395-01199980-71e0-11eb-815d-3ec6c8bf680c.png)

Link: https://github.com/stuartd/keymapper/releases/download/1.1/KeyMapper.exe
