### ISSUE TITLE
KeyMapper.exe does not open

### ISSUE THREAD

**Issue by StacktraceException** [stuartd/keymapper#24]
Nothing happens when I try to open the file. Program is thusly useless. Windows 11.

**Comment by stuartd** [comment]
> Nothing happens when I try to open the file. Program is thusly useless. Windows 11.

Possibly .Net framework version. Anything relevant in the event log?

**Comment by stuartd** [comment]
Created a Win11 VM for testing. Previous version did not run, but showed this message:

<img width="659" alt="Screenshot 2022-12-06 at 12 12 37" src="https://user-images.githubusercontent.com/275326/205920791-a220f19f-1997-4aa1-9fe0-137bebf8296f.png">

So created a new release for Win11: - https://github.com/stuartd/keymapper/releases/download/1.2/KeyMapper.exe

This worked on Win11.


<img width="964" alt="Screenshot 2022-12-06 at 13 09 04" src="https://user-images.githubusercontent.com/275326/205921412-f4450477-50bb-4da5-98c0-1841547fe9bd.png">

**Comment by stuartd** [comment]
@StacktraceException does this work for you?

**Comment by StacktraceException** [comment]
Sorry, I did not see your messages, as my inbox did not notify me of them.
I did not ever see a message from Windows about missing .Net framework, but
I shall try to install the one in the image.

Thank you for replying, I will let you know soon, (I hope).

Regards :).

wt., 6 gru 2022, 14:11 użytkownik stuartd ***@***.***>
napisał:
