### ISSUE TITLE
1.3 doesn't let me boot my mappings. Windows 10.

### ISSUE THREAD

**Issue by clovxz** [stuartd/keymapper#26]
![image](https://github.com/stuartd/keymapper/assets/160629585/22473006-8f2a-49f3-b13e-428cc897dfef)

**Comment by stuartd** [comment]
Sorry I missed this, I’ll take a look

**Comment by stuartd** [comment]
Not quite sure what you mean by “boot my mappings” though?

**Comment by stuartd** [comment]
That menu item was empty anyway, as the whole concept of 'boot' and 'user' mappings went away in Windows 7, so the project readme is misleading for the new version as it's intended for people using earlier versions.

So I've removed the menu items, and it's really about time I updated the readme as well..
