### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by abdullahfazeel** [stuartd/keymapper#28]
Please update the Link in Read Me to Release 1.4
Clicking the Link given in Read Me gives **Error 404 - page not found**
Cannot find a valid ref in develop/KeyMapper.exe

**Comment by stuartd** [comment]
Thanks, will do!

**Comment by stuartd** [comment]
Fixed, current download is https://github.com/stuartd/keymapper/releases/download/1.4/KeyMapper.exe
