### ISSUE TITLE
Can you make it so different apps can have different profiles? Kinda like what antimicrox did

### ISSUE THREAD

**Issue by ProGHost00** [stuartd/keymapper#29]
Basically make it so it would read if a program I already created a key map profile for is running and activate that profile of key mapping.

**Comment by stuartd** [comment]
There are programs which work at runtime to transform keystrokes in the way you want, but not this one.

This program uses registry settings to set the key mappings for the whole system, to have different mappings per-program means remapping keys at runtime depending on what program is currently active.
